Create: 앱 생성 및 모델 마이그레이션
wecode-bootcamp-korea/26-1st-WETCHAPEDIA-backend pull request #1
Opened 2021-11-02 11:01 UTC by Jang-Jaewon

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [x] 기능 추가
- [x] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [x] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
- 앱 생성 및 Modeling 테이블 생성

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
1. users app, movies앱 생성
- 앱 생성 및 앱 등록

2. 모델링 결과 테이블 생성
- users/models.py 및 movies/models.py 테이블 생성
- 마이그레이션 완료

<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)
- soft delete 기능 이해 및 구현
- many-to-many 필드 사용 유무에 따른 차이 이해

<br />

## :: 기타 질문 및 특이 사항
- 반드시 앞으로 branch를 미리 생성하고 작업을 시작하겠습니다.

2021-11-02 15:08 UTC, jamessoun93 requested changes
모델 작성하시느라 수고많으셨습니다! 💯
전체적으로 깔끔하고 제가 리뷰때 말씀드렸던 내용이 아주 잘 반영되어 있는 것 같아서 기분이 좋네요 👍 
다만, 전체적으로 `created_at`, `updated_at` 이 불필요하게 많이 들어가있는 것 같아서 다시한번 보면서 여기에 `created_at`, `updated_at` 이 꼭 필요할 지 고민해보면서 전체적으로 검토를 해주셨으면 좋겠습니다!

2021-11-02 15:08 UTC, jamessoun93 commented on movies/models.py
> +# Create your models here.
불필요한 주석은 없애주세요!

2021-11-02 15:08 UTC, jamessoun93 commented on movies/models.py
> +    updated_at = models.DateTimeField(auto_now=True)
혹시 `Grade` 테이블에 `created_at` 과 `updated_at` 은 어떤 목적으로 추가하셨을까요?

2021-11-02 15:08 UTC, jamessoun93 commented on movies/models.py
> +    updated_at = models.DateTimeField(auto_now=True)
여기도 굳이 필요할까요?!

2021-11-02 15:08 UTC, jamessoun93 commented on users/models.py
> +# Create your models here.
여기도 불필요한 주석 없애주세요!

2021-11-03 04:33 UTC, Jang-Jaewon commented on movies/models.py
> +# Create your models here.
불필요한 주석 제거하였습니다!

2021-11-03 04:36 UTC, Jang-Jaewon commented on movies/models.py
> +    updated_at = models.DateTimeField(auto_now=True)
Grade 테이블, Source 테이블, Staff 테이블, Genre 테이블, 중계 테이블에 불필요한 created_at과 updated_at 삭제하였습니다!

2021-11-03 04:36 UTC, Jang-Jaewon commented on movies/models.py
> +    updated_at = models.DateTimeField(auto_now=True)
Grade 테이블, Source 테이블, Staff 테이블, Genre 테이블, 중계 테이블에 불필요한 created_at과 updated_at 삭제하였습니다!

2021-11-03 04:38 UTC, Jang-Jaewon commented
추가 테이블 변경 사항 기록 말씀드립니다.
users앱에 deleted_at 필드가 auto_now=True로 되어있었습니다. 이제 파악하여 null=True로 수정하였습니다.

2021-11-03 04:54 UTC, jamessoun93 commented
> 추가 테이블 변경 사항 기록 말씀드립니다. users앱에 deleted_at 필드가 auto_now=True로 되어있었습니다. 이제 파악하여 null=True로 수정하였습니다.

오오 넵 수고하셨습니다!

2021-11-03 04:55 UTC, jamessoun93 approved these changes
LGTM 💯 🚀

2021-11-03 04:56 UTC, merged