로그인, 회원가입, 토큰 인증 데코레이터 기능 구현
wecode-bootcamp-korea/26-1st-WETCHAPEDIA-backend pull request #3
Opened 2021-11-05 04:23 UTC by minjeongcode

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [X] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
- 아이디, 비밀번호 입력창을 사용한 로그인 기능 구현
- 토큰 인증을 위한 데코레이터 기능 구현

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
1. 로그인, 회원가입 데이터 처리
- 조건문과 정규식을 이용한 email과 password 유효성 검사를 진행
- 유효섬 검사를 통과하지 못 할 경우 에러 메시지를 반환 예외 처리 구현

2. 패스워드 암호화 및 복호화
- bcrypt를 이용하여 패스워드를 암호화하고 복호화하여 로그인 할 수 있는 기능 구현

3. JWT 토큰 발행
- 로그인 시 토큰 발행될 수 있도록 처리

4. login decorator 작성
- 토큰이 필요한 곳에 데코레이터로 불러올 수 있도록 함수 작성함.

<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)
- 위스타그램 때 했던 회원가입 로그인 구현을 복습하고 새롭게 해보기 위해 try문의 assert를 이용해서 작성도 해보았으나 jsonresponse으로 출력하는 방법을 찾기 어려워 다시 배웠던 if not 처리로 돌아가는 과정을 거쳤습니다. 그래도 새로운 방법도 알게 되었으니 재밌었습니다.
- 데코레이터 함수 작성 부분이 어려워서 다른사람 코드를 보며 쳐봤는데 아직도 이해가 잘 안되는 것 같습니다. 그래서 관련 개념과 코드들을 많이 보면서 눈에 익히고 이해하는 과정을 거쳐야 할 것 같습니다.... 
<br />

## :: 기타 질문 및 특이 사항
-

2021-11-05 08:25 UTC, jamessoun93 requested changes
코드가 전체적으로 매우매우 깔끔하네요! 👍
아주 minor 한 피드백 남겨드렸으니 반영해서 수정해주세요!

2021-11-05 08:25 UTC, jamessoun93 commented on users/views.py
> +            return JsonResponse({'message' : 'SUCCESS', 'ACCESS_TOKEN' : access_token}, status = 200)
json body 의 key 값은 소문자로 통일시켜주세요!

2021-11-05 08:25 UTC, jamessoun93 commented on users/views.py
> +                return JsonResponse({'message' : 'SAME_VALUE_ERROR'}, status = 400)
`SAME_VALUE_ERROR` 보다는 더 명확한 메세지가 좋을 것 같네요!

2021-11-05 09:21 UTC, minjeongcode commented on users/views.py
> +            return JsonResponse({'message' : 'SUCCESS', 'ACCESS_TOKEN' : access_token}, status = 200)
'ACCESS_TOKEN' -> 'access_token' 으로 수정하였습니다.

2021-11-05 09:21 UTC, minjeongcode commented on users/views.py
> +                return JsonResponse({'message' : 'SAME_VALUE_ERROR'}, status = 400)
'SAME_VALUE_ERROR' -> 'DUPLICATE_EMAIL_ERROR' 으로 수정하였습니다.

2021-11-06 06:55 UTC, jamessoun93 approved these changes
LGTM 💯
수고하셨습니다!

2021-11-06 06:55 UTC, merged