Create: 평균 평점 기준 영화 리스트 API 생성
wecode-bootcamp-korea/26-1st-WETCHAPEDIA-backend pull request #4
Opened 2021-11-05 10:15 UTC by Jang-Jaewon

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [x] 기능 추가
- [x] 리뷰 반영
- [x] 리팩토링
- [ ] 버그 수정
- [x] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
- 프론트에서 전달한 query parameter를 이용해 평균 평점 기준으로 영화 리스트를 조회해주는 API를 생성

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
1. 메인 페이지 영화 리스트 기능 구현
-  박스오피스, 왓챠, 넷플릭스 관련 평균 평점 높은 영화 리스트 출력 기능
- query parameter로 rating이 전달되면, 전체 영화에서 평균 평점이 높은 영화 목록 제공
- 영화 목록은 최대 15개까지 조회하여 전달

2. 검색 기능 구현
- 영화 제목 기준으로 검색어 입력하면, 검색 내용이 포함된 영화 리스트를 평균 평점 순위로 나열하여 15개까지 전달

<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)
- Q객체를 add하여 사용하는 방법에 대해 익혔습니다.
- annotate를 사용하여 Many-to-Many를 통해 참조하는 평점을 찾아 평균을 구하는 방법에 대해서 배웠습니다.
- 웹브라우저 URI와 상관없이 프로늩에서 fetch 통해 request를 여러번 요청할 수 있다는 사실에서 대해서 알게되었습니다.
- 또한 앞으로 API를 설계할 때 로직의 확장성에 대한 고려를 함께 할 수 있는 기회가 되었습니다.

<br />

## :: 기타 질문 및 특이 사항
- source 필드 및 테이블을 추후 platform으로 수정하여 마이그레이션 할 수 있도록 하겠습니다.

2021-11-06 08:41 UTC, jamessoun93 requested changes
리뷰남겨드렸습니다 재원님! 😉
반영해서 push 해주세요 🙏

2021-11-06 08:41 UTC, jamessoun93 commented on movies/views.py
> +        OFFSET = 0
- `LIMIT` 과 `OFFSET` 은 무조건 각각 `15` 와 `0` 고정값인가요?
- 보통 `LIMIT` 과 `OFFSET` 은 가변값이라 프론트에서 query parameter 형태로 넣어주는게 좋습니다.

2021-11-06 08:41 UTC, jamessoun93 commented on movies/views.py
> +            q.add(Q(title__icontains=title), q.AND)
field lookups 잘 활용하셨습니다 👍👍👍

2021-11-06 08:41 UTC, jamessoun93 commented on movies/views.py
> +            .order_by("-average_point")[OFFSET:LIMIT]
`annotate` 활용 gooood! 👍 
 
하지만 `[OFFSET:LIMIT]` 부분은 문제가 있습니다. 지금은 `OFFSET` 과 `LIMIT` 이 각각 `0` 과 `15`로 고정값이라 이렇게해도 상관없지만 위에서 리뷰 남겨드린대로 `offset`, `limit` 은 보통 가변값입니다.

한 페이지당 10개씩 보여줘야할때 프론트에서 2번째 페이지에 해당하는 list 요청을 날린다면 `LIMIT` 과 `OFFSET` 은 각각 `15`, `15` 겠죠? 3페이지 같은 경우는 어떨까요? 

이 부분 고민해보시고 수정해보세요! 💪

2021-11-06 08:41 UTC, jamessoun93 commented on movies/views.py
> +                    "ratings": movie.average_point,
통신결과를 보니 불필요하게 많은 소수점까지 찍혀서 보내지는데 소수점 한자리로 끊어서 보내주는게 좋을 것 같네요!

2021-11-06 08:42 UTC, jamessoun93 commented
그리고 conflict 해결해주세요~

2021-11-06 11:20 UTC, Jang-Jaewon commented on movies/views.py
> +            .order_by("-average_point")[OFFSET:LIMIT]
리뷰주신 내용을 고민한 결과가 pagination 기능으로 이해하였습니다. page와 display값을 프론트에서 query parameter 형태로 전달받도록 수정하였습니다. page는 요청된 페이지이고, display값은 페이지당 보여줄 객체의 갯수입니다. 이 값을 받아 LIMIT와 OFFSET 값을 산출하여 반환할 수 있도록 처리하였습니다.

2021-11-06 11:21 UTC, Jang-Jaewon commented on movies/views.py
> +            .order_by("-average_point")[OFFSET:LIMIT]
리뷰주신 내용을 고민한 결과가 pagination 기능으로 이해하였습니다. page와 display값을 프론트에서 query parameter 형태로 전달받도록 수정하였습니다. page는 요청된 페이지이고, display값은 페이지당 보여줄 객체의 갯수입니다. 이 값을 받아 LIMIT와 OFFSET 값을 산출하여 반환할 수 있도록 처리하였습니다.

2021-11-06 11:23 UTC, Jang-Jaewon commented on movies/views.py
> +                    "ratings": movie.average_point,
불필요한 소수점을 제거하기 위해 round 함수를 사용하여 소수 첫재짜리 까지 처리하였습니다. 평점이 아직 없는 영화는 None값 가지는데 이를 round함수를 사용하면 에러가 발생되었습니다. 이에 삼항연사자를 사용하여 값이 None이 아니면 처리한 결과를 전달하고 None이면 0을 반환할 수 있도록 하였습니다.

2021-11-06 11:26 UTC, Jang-Jaewon commented on movies/views.py
> +        OFFSET = 0
아래 리뷰 사항에 반영사항 함께 작성하였습니다.

2021-11-06 11:26 UTC, Jang-Jaewon commented on movies/views.py
> +            q.add(Q(title__icontains=title), q.AND)
감사합니다!

2021-11-06 11:26 UTC, Jang-Jaewon commented
1. 영화리스트 제공하는데 그 수를 제어할 수 있도록 display, page 값을 query parameter로 전달 받을 수 있도록 수정하였습니다.
2. 소수 첫재짜리까지 평균 평점을 정제하고, None값이면 0을 반환할 수 있도록 수정하였습니다.
3. conflict 해결 완료하였습니다.

2021-11-07 09:28 UTC, Jang-Jaewon commented on movies/views.py
> +        OFFSET = LIMIT - page_size
수정사항 반영하였습니다! 제가 잘못 생각해써 page값을 받아버려서 불필요한 처리를 하였네요! 수정사항 올바른지 말씀부탁드립니다! 감사합니다!

2021-11-07 09:32 UTC, jamessoun93 requested changes
리뷰 남겨드렸습니다!
실제 SQL에서 LIMIT, OFFSET 이 무슨 역할을 하는지 조금 살펴보시면 더 이해가 잘 되실 듯 해요!

2021-11-07 09:32 UTC, jamessoun93 commented on movies/views.py
> +        OFFSET = LIMIT - page_size
> 리뷰주신 내용을 고민한 결과가 pagination 기능으로 이해하였습니다. page와 display값을 프론트에서 query parameter 형태로 전달받도록 수정하였습니다. page는 요청된 페이지이고, display값은 페이지당 보여줄 객체의 갯수입니다. 이 값을 받아 LIMIT와 OFFSET 값을 산출하여 반환할 수 있도록 처리하였습니다.

말씀하신 `page_size` 가 우리가 원하는 `LIMIT` 값으로 보이는데 `page_size * page` 를 해주고 계시네요? 한번 확인해주세요.

2021-11-07 09:32 UTC, jamessoun93 commented on movies/views.py
> +                    "ratings": round(movie.average_point, 1) if movie.average_point != None else 0,
ternary operator 사용 👍 입니다!

2021-11-07 12:23 UTC, jamessoun93 requested changes

2021-11-07 12:23 UTC, jamessoun93 commented on movies/views.py
> +        LIMIT = OFFSET + page_size
흠 `LIMIT` 은 제가 말씀드린대로 `page_size` 를 그대로 받아 사용하면 되는 값이지 계산하는 값이 아닙니다.
`OFFSET` 을 계산해서 `[OFFSET:OFFSET+LIMIT]` 의 형태가 되어야합니다.

2021-11-07 13:17 UTC, Jang-Jaewon commented on movies/views.py
> +        LIMIT = OFFSET + page_size
OFFSET은 Slice의 시작점이고, LIMIT은 페이지당 보여줄 row의 수량이라는 개념을 계속 이해하지 못하는데도...
친절히 알려주셔서 정말 감사합니다!
수정사항 반영하였습니다!  🙏

2021-11-07 13:48 UTC, jamessoun93 approved these changes
LGTM 👍

2021-11-07 13:48 UTC, merged