GET 영화 상세페이지 API 생성
wecode-bootcamp-korea/26-1st-WETCHAPEDIA-backend pull request #5
Opened 2021-11-05 14:39 UTC by 1119pdh

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [x] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 
- 프론트에서 요청하는 URI에 맞는 영화 상세페이지 API 생성

<br />

## :: 구현 사항 설명 
1. URL 경로 업데이트(임시)
- config.urls.py  모든 데이터 movie.urls.py로 갈 수 있게 설정
- movies.urls.py 영화 아이디에 맞게 영화 데이터 반환하는 API 설정

2. MovieDetailView get 메서드 작성
- 미리 협의한 목데이터를 바탕으로 프론트에서 요청한 id 값에 맞는 영화 데이터 반환

3. MovieDetailView 에러 처리 
- try, except을 이용해 에러 발생시 에러에 맞는 메세지 반환
- movie 테이블에 없는 id값을 요청시 "영화 정보가 없습니다" 메세지 반환
- keyError 발생시 "KEY_ERROR" 메세지 반환

<br />

## :: 성장 포인트 
- 많은 매니 투 매니 관계 테이블을 거치면서 참조와 역참조 방법을 정확하게 알았다.
- 특정 값만 가지고 올 때 get을 이용하는 상황과 filter를 이용하는 상황, for문을 이용한 리스트 컴프리헨션을 이용하는 상황을 구별할 수 있게 되었다.

<br />

## :: 기타 질문 및 특이 사항
- [13, 51]프론트에서 리스트에 담은 데이터가 아닌 딕셔너리 형태의 데이터를 요청합니다. 지금 result에서 []를 빼고 반환 가능한가요? 리스트에 담지 않고, 반환을 하려하니 오류가 납니다. result={}해서 딕셔너리안에 딕셔너리를 넣는것도 아니고, 지금 값에서 []를 뺀값을 요청합니다. 
- [29~39]37번에 for staff in movie.staffs_set.all()을 해서, name과 profile_image_url을 참조하고, position과 role을 역참조해서 가지고 올려고 했는데 _set을 사용해도 불가능합니다. 불가능한 이유가 있나요? 
-[53~54]except에 KeyError를 넣었는데 KeyError가 나오는 상황이 있나요?
-[53~57]이 오류말고 사용자에게 보여줄만한 오류가 있을까요? except 오류는 오직 사용자에게 보여주는 메세지를 작성하는건가요?

2021-11-06 09:04 UTC, jamessoun93 requested changes
리뷰남겨드렸습니다 대현님! 🤗
반영해서 push 해주세요! 😉

2021-11-06 09:04 UTC, jamessoun93 commented on movies/urls.py
> +    path("movies/<int:pk>", MovieDetailView.as_view())
`pk` 보다는 `movie_id` 이런 식으로 더 명확하게 지어주시면 좋겠네요!

2021-11-06 09:04 UTC, jamessoun93 commented on movies/views.py
> +            )
가독성을 위해 list comprehension 으로 변경해보세요!

2021-11-06 09:04 UTC, jamessoun93 commented on movies/migrations/0001_initial.py
>  from django.db import migrations, models
migration 관련 변경사항은 꼭 브랜치 따로 생성하여 우선적으로 머지될 수 있도록 해주세요 😉

2021-11-06 09:04 UTC, jamessoun93 commented on movies/views.py
> +                        }
반환해주는 json body 의 key 값들이 camelCase 로 되어있는데 이 부분은 백엔드 전체적으로 이야기하여 맞춰주셔야합니다. 재원님은 snake_case 를 활용하고 계셔서요. 저희는 python 으로 개발하고 있으니 snake_case 로 통일해주시는게 좋아보이네요!

2021-11-06 09:04 UTC, jamessoun93 commented on movies/views.py
> +            return JsonResponse({"message" : "영화 정보가 없습니다."}, status=401)
영화정보가 없는데 `401` 은 상황에 맞지 않는 HTTP Status Code 입니다! 
`401` 의 뜻이 무엇인가요? 알아보시고 상황에 맞는 status code 로 수정해주세요 😉

2021-11-07 06:31 UTC, 1119pdh commented on movies/urls.py
> +    path("movies/<int:pk>", MovieDetailView.as_view())
변경했습니다!

2021-11-07 06:31 UTC, 1119pdh commented on movies/migrations/0001_initial.py
>  from django.db import migrations, models
넵 동일한 초기셋팅을 마이그레이션 한건데 주석의 시간만 바꿔도 상관없을까요??
코드내용은 동일합니다.

2021-11-07 06:32 UTC, 1119pdh commented on movies/views.py
> +                        }
snake_case로 통일했습니다.

2021-11-07 06:33 UTC, 1119pdh commented on movies/views.py
> +            return JsonResponse({"message" : "영화 정보가 없습니다."}, status=401)
404 리소스 없음으로 변경했습니다.

2021-11-07 06:34 UTC, 1119pdh commented on movies/views.py
> +            )
변경했습니다!

2021-11-07 10:16 UTC, 1119pdh commented
컨플릭트 해결 했습니다!

2021-11-07 12:25 UTC, jamessoun93 requested changes

2021-11-07 12:25 UTC, jamessoun93 commented on movies/urls.py
> +    path("movies/<int:movie_id>", MovieDetailView.as_view())
여기서 movies 를 포함시켜줄 필요없이 root urls.py 에서 해줄 수 있습니다.

2021-11-07 12:25 UTC, jamessoun93 commented on movies/views.py
> +            results = [
여기서 result 를 list 로 감싸서 리턴해주는 이유가 있을까요?
list 는 여러개를 담기 위한 자료구조인데 여기서는 한개의 영화정보만 리턴해주면 되니까요.

2021-11-08 01:58 UTC, 1119pdh commented on movies/urls.py
> +    path("movies/<int:movie_id>", MovieDetailView.as_view())
수정했습니다!

2021-11-08 02:00 UTC, 1119pdh commented
컨플릭트 해결하고 태그변경하겠습니다

2021-11-08 02:14 UTC, 1119pdh commented on movies/views.py
> +            results = [
목데이터에 맞게 코멘트를 영화 상세정보와 나눠서 주려고 리스트에 넣었습니다.

프론트와 다시 상의한 결과 영화 상세정보와 스태프, 코멘트를 나눠서 리스트에 넣어 주는게 합쳐서 주는것 보다 편하다고 해서 다시 수정했습니다!

2021-11-08 11:14 UTC, 1119pdh commented on movies/views.py
> +            results = [
다시 바꿧습니다! 감사합니다

2021-11-08 14:30 UTC, jamessoun93 approved these changes
LGTM 🚀

2021-11-08 14:30 UTC, jamessoun93 commented on movies/views.py
> +            }
이 부분 조금 더 깔끔하게 정리하고 싶은데 이 부분은 페어프로그래밍 세션때 따로 진행하겠습니다!

2021-11-08 14:30 UTC, merged